"""empty message

Revision ID: 1cb52f9eef83
Revises: 960122f4588a
Create Date: 2019-10-19 11:21:00.486960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb52f9eef83'
down_revision = '960122f4588a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traditional_authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traditional_authorities_name'), 'traditional_authorities', ['name'], unique=False)
    op.create_table('childrens_corner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ta_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['ta_id'], ['traditional_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_childrens_corner_name'), 'childrens_corner', ['name'], unique=False)
    op.create_table('community_victim_support_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ta_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['ta_id'], ['traditional_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_victim_support_units_name'), 'community_victim_support_units', ['name'], unique=False)
    op.add_column('locations', sa.Column('iso_id', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_locations_iso_id'), 'locations', ['iso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_iso_id'), table_name='locations')
    op.drop_column('locations', 'iso_id')
    op.drop_index(op.f('ix_community_victim_support_units_name'), table_name='community_victim_support_units')
    op.drop_table('community_victim_support_units')
    op.drop_index(op.f('ix_childrens_corner_name'), table_name='childrens_corner')
    op.drop_table('childrens_corner')
    op.drop_index(op.f('ix_traditional_authorities_name'), table_name='traditional_authorities')
    op.drop_table('traditional_authorities')
    # ### end Alembic commands ###
