"""empty message

Revision ID: 5fadea3505f2
Revises: 3b9f43b64a50
Create Date: 2019-07-26 08:17:42.715911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fadea3505f2'
down_revision = '3b9f43b64a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_stations', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('police_stations', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('police_stations', 'longitude')
    op.drop_column('police_stations', 'latitude')
    # ### end Alembic commands ###
