"""empty message

Revision ID: 80dcc3b519b9
Revises: 8229acbe3f6c
Create Date: 2019-09-04 17:17:48.754998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dcc3b519b9'
down_revision = '8229acbe3f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cases', sa.Column('summary_slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_summary_cases_summary_slug'), 'summary_cases', ['summary_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_cases_summary_slug'), table_name='summary_cases')
    op.drop_column('summary_cases', 'summary_slug')
    # ### end Alembic commands ###
