"""empty message

Revision ID: 8229acbe3f6c
Revises: bffd880293fb
Create Date: 2019-09-01 13:14:23.169053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8229acbe3f6c'
down_revision = 'bffd880293fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cases', sa.Column('summary_for', sa.String(), nullable=True))
    op.create_index(op.f('ix_summary_cases_summary_for'), 'summary_cases', ['summary_for'], unique=False)
    op.drop_index('ix_summary_cases_summary_type', table_name='summary_cases')
    op.drop_column('summary_cases', 'summary_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cases', sa.Column('summary_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_summary_cases_summary_type', 'summary_cases', ['summary_type'], unique=False)
    op.drop_index(op.f('ix_summary_cases_summary_for'), table_name='summary_cases')
    op.drop_column('summary_cases', 'summary_for')
    # ### end Alembic commands ###
