"""empty message

Revision ID: 83eb91938dbe
Revises: 3524c3e71112
Create Date: 2019-07-18 17:36:23.177835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83eb91938dbe'
down_revision = '3524c3e71112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_category'), 'indicators', ['category'], unique=False)
    op.create_index(op.f('ix_indicators_report_type'), 'indicators', ['report_type'], unique=False)
    op.create_index(op.f('ix_indicators_slug'), 'indicators', ['slug'], unique=False)
    op.drop_index('ix_indicator_category', table_name='indicator')
    op.drop_index('ix_indicator_report_type', table_name='indicator')
    op.drop_index('ix_indicator_slug', table_name='indicator')
    op.drop_table('indicator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='indicator_pkey')
    )
    op.create_index('ix_indicator_slug', 'indicator', ['slug'], unique=False)
    op.create_index('ix_indicator_report_type', 'indicator', ['report_type'], unique=False)
    op.create_index('ix_indicator_category', 'indicator', ['category'], unique=False)
    op.drop_index(op.f('ix_indicators_slug'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_report_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_category'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
