"""empty message

Revision ID: 960122f4588a
Revises: 80dcc3b519b9
Create Date: 2019-09-28 13:03:52.005562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '960122f4588a'
down_revision = '80dcc3b519b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cases', sa.Column('json_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_summary_cases_json_values'), 'summary_cases', ['json_values'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_cases_json_values'), table_name='summary_cases')
    op.drop_column('summary_cases', 'json_values')
    # ### end Alembic commands ###
