"""empty message

Revision ID: 9a194a3e0f65
Revises: 75946a9e8589
Create Date: 2019-10-23 15:58:28.351083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a194a3e0f65'
down_revision = '75946a9e8589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'latitude')
    # ### end Alembic commands ###
