"""empty message

Revision ID: ab069084ce20
Revises: 5fadea3505f2
Create Date: 2019-07-26 14:52:51.213465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab069084ce20'
down_revision = '5fadea3505f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flow_data_values'), 'flow_data', ['values'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_data_values'), table_name='flow_data')
    # ### end Alembic commands ###
