"""empty message

Revision ID: bffd880293fb
Revises: dc25209c03c1
Create Date: 2019-09-01 13:10:34.459801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffd880293fb'
down_revision = 'dc25209c03c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casetype', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('court', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('summary_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['court'], ['justice_courts.id'], ),
    sa.ForeignKeyConstraint(['district'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['station'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_cases_casetype'), 'summary_cases', ['casetype'], unique=False)
    op.create_index(op.f('ix_summary_cases_month'), 'summary_cases', ['month'], unique=False)
    op.create_index(op.f('ix_summary_cases_report_type'), 'summary_cases', ['report_type'], unique=False)
    op.create_index(op.f('ix_summary_cases_summary_type'), 'summary_cases', ['summary_type'], unique=False)
    op.create_index(op.f('ix_summary_cases_year'), 'summary_cases', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_cases_year'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_summary_type'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_report_type'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_month'), table_name='summary_cases')
    op.drop_index(op.f('ix_summary_cases_casetype'), table_name='summary_cases')
    op.drop_table('summary_cases')
    # ### end Alembic commands ###
