"""empty message

Revision ID: dc25209c03c1
Revises: ab069084ce20
Create Date: 2019-08-12 18:54:42.835281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc25209c03c1'
down_revision = 'ab069084ce20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('justice_courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_justice_courts_name'), 'justice_courts', ['name'], unique=False)
    op.add_column('flow_data', sa.Column('court', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flow_data', 'justice_courts', ['court'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow_data', type_='foreignkey')
    op.drop_column('flow_data', 'court')
    op.drop_index(op.f('ix_justice_courts_name'), table_name='justice_courts')
    op.drop_table('justice_courts')
    # ### end Alembic commands ###
