"""empty message

Revision ID: f01bce11dc65
Revises:
Create Date: 2019-07-17 01:32:46.232930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Text

# revision identifiers, used by Alembic.
revision = 'f01bce11dc65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationtree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationtree_name'), 'locationtree', ['name'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['locationtree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('locations_level_idx', 'locations', ['level'], unique=False)
    op.create_index('locations_lft_idx', 'locations', ['lft'], unique=False)
    op.create_index('locations_rgt_idx', 'locations', ['rgt'], unique=False)
    op.create_table('police_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_stations_name'), 'police_stations', ['name'], unique=False)
    op.create_table('flow_data',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('msisdn', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['station'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_data_month'), 'flow_data', ['month'], unique=False)
    op.create_index(op.f('ix_flow_data_msisdn'), 'flow_data', ['msisdn'], unique=False)
    op.create_index(op.f('ix_flow_data_report_type'), 'flow_data', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_data_report_type'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_msisdn'), table_name='flow_data')
    op.drop_index(op.f('ix_flow_data_month'), table_name='flow_data')
    op.drop_table('flow_data')
    op.drop_index(op.f('ix_police_stations_name'), table_name='police_stations')
    op.drop_table('police_stations')
    op.drop_index('locations_rgt_idx', table_name='locations')
    op.drop_index('locations_lft_idx', table_name='locations')
    op.drop_index('locations_level_idx', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_locationtree_name'), table_name='locationtree')
    op.drop_table('locationtree')
    # ### end Alembic commands ###
